version: '3'

services:
  map:
    build: .
    environment:
      REPLICATION_URL: https://planet.osm.ch/replication/hour/
      MAX_INTERVAL_SECONDS: "3500"
      UPDATES: enabled
      DOWNLOAD_PBF: https://planet.osm.ch/switzerland-padded.osm.pbf
      DOWNLOAD_POLY: https://planet.osm.ch/switzerland-padded.poly
    volumes:
      - osm-tiles:/data/tiles/
      - osm-data:/data/database/
      - ./osm-carto-alternative-colors:/data/style/
      - ./html:/data/html/
    ports:
      - "8080:80"
    command: "run"

volumes:
  osm-data:
    external: true
  osm-tiles:
    external: true
